CREATE OR REPLACE TABLE IPRA_DB.STAGING.CLIENT_STAGE (
    CLIENT_ID VARCHAR,
    CLIENT_NAME VARCHAR,
    CLIENT_TYPE VARCHAR,
    COUNTRY VARCHAR,
    RISK_PROFILE VARCHAR,
    CREATED_DATE VARCHAR,
    STATUS VARCHAR
)
COMMENT = 'Staging for client data';

CREATE OR REPLACE TABLE IPRA_DB.STAGING.PORTFOLIO_STAGE (
    PORTFOLIO_ID VARCHAR,
    CLIENT_ID VARCHAR,
    PORTFOLIO_NAME VARCHAR,
    PORTFOLIO_TYPE VARCHAR,
    BASE_CURRENCY VARCHAR,
    RISK_PROFILE VARCHAR,
    INITIAL_VALUE VARCHAR,
    CURRENT_VALUE VARCHAR,
    INCEPTION_DATE VARCHAR,
    STATUS VARCHAR
)
COMMENT = 'Staging for portfolio data';

CREATE OR REPLACE TABLE IPRA_DB.STAGING.SECURITY_STAGE (
    SECURITY_ID VARCHAR,
    TICKER_SYMBOL VARCHAR,
    SECURITY_NAME VARCHAR,
    SECURITY_TYPE VARCHAR,
    SECTOR VARCHAR,
    COUNTRY VARCHAR,
    CURRENCY VARCHAR,
    CURRENT_PRICE VARCHAR,
    STATUS VARCHAR
)
COMMENT = 'Staging for security data';

CREATE OR REPLACE TABLE IPRA_DB.STAGING.HOLDING_STAGE (
    HOLDING_ID VARCHAR,
    PORTFOLIO_ID VARCHAR,
    SECURITY_ID VARCHAR,
    QUANTITY VARCHAR,
    PURCHASE_PRICE VARCHAR,
    CURRENT_PRICE VARCHAR,
    MARKET_VALUE VARCHAR,
    AS_OF_DATE VARCHAR
)
COMMENT = 'Staging for holding data';

CREATE OR REPLACE TABLE IPRA_DB.STAGING.PERFORMANCE_STAGE (
    PERFORMANCE_ID VARCHAR,
    PORTFOLIO_ID VARCHAR,
    AS_OF_DATE VARCHAR,
    BEGINNING_VALUE VARCHAR,
    ENDING_VALUE VARCHAR,
    RETURN_AMOUNT VARCHAR,
    RETURN_PERCENT VARCHAR
)
COMMENT = 'Staging for performance data';

-- Verify staging tables
SHOW TABLES IN SCHEMA IPRA_DB.STAGING;