-- ==========================================
-- Validation Queries
-- Purpose: Check data quality issues in CORE tables
-- ==========================================

-- 1. Check for duplicate portfolio IDs
SELECT 'DUPLICATE_PORTFOLIO_IDS' AS CHECK_NAME,
       PORTFOLIO_ID, COUNT(*) AS DUPLICATE_COUNT
FROM IPRA_DB.CORE.PORTFOLIO
GROUP BY PORTFOLIO_ID
HAVING COUNT(*) > 1;

-- 2. Check for orphan portfolios (no client)
SELECT 'ORPHAN_PORTFOLIOS' AS CHECK_NAME,
       p.PORTFOLIO_ID, p.CLIENT_ID
FROM IPRA_DB.CORE.PORTFOLIO p
LEFT JOIN IPRA_DB.CORE.CLIENT c ON p.CLIENT_ID = c.CLIENT_ID
WHERE c.CLIENT_ID IS NULL;

-- 3. Check for orphan holdings (no portfolio or no security)
SELECT 'ORPHAN_HOLDINGS' AS CHECK_NAME,
       h.HOLDING_ID, h.PORTFOLIO_ID, h.SECURITY_ID
FROM IPRA_DB.CORE.HOLDING h
LEFT JOIN IPRA_DB.CORE.PORTFOLIO p ON h.PORTFOLIO_ID = p.PORTFOLIO_ID
LEFT JOIN IPRA_DB.CORE.SECURITY s ON h.SECURITY_ID = s.SECURITY_ID
WHERE p.PORTFOLIO_ID IS NULL OR s.SECURITY_ID IS NULL;

-- 4. Check for negative portfolio values
SELECT 'NEGATIVE_PORTFOLIO_VALUES' AS CHECK_NAME,
       PORTFOLIO_ID, INITIAL_VALUE, CURRENT_VALUE
FROM IPRA_DB.CORE.PORTFOLIO
WHERE INITIAL_VALUE < 0 OR CURRENT_VALUE < 0;

-- 5. Check for negative/zero security prices
SELECT 'NEGATIVE_SECURITY_PRICES' AS CHECK_NAME,
       SECURITY_ID, TICKER_SYMBOL, CURRENT_PRICE
FROM IPRA_DB.CORE.SECURITY
WHERE CURRENT_PRICE <= 0;

-- 6. Check for negative holding quantities
SELECT 'NEGATIVE_HOLDING_QUANTITIES' AS CHECK_NAME,
       HOLDING_ID, QUANTITY
FROM IPRA_DB.CORE.HOLDING
WHERE QUANTITY <= 0;

-- 7. Check for null mandatory fields
SELECT 'NULL_MANDATORY_FIELDS' AS CHECK_NAME,
       COUNT(*) AS NULL_COUNT
FROM IPRA_DB.CORE.PORTFOLIO
WHERE PORTFOLIO_ID IS NULL OR CLIENT_ID IS NULL;