-- ==========================================
-- Reconciliation Queries
-- Purpose: Compare STAGING vs CORE counts
-- ==========================================

-- 1. STAGING vs CORE record count comparison
SELECT 'CLIENTS' AS TABLE_NAME,
       (SELECT COUNT(*) FROM IPRA_DB.STAGING.CLIENT_STAGE) AS STAGING_COUNT,
       (SELECT COUNT(*) FROM IPRA_DB.CORE.CLIENT) AS CORE_COUNT,
       (SELECT COUNT(*) FROM IPRA_DB.STAGING.CLIENT_STAGE) - 
       (SELECT COUNT(*) FROM IPRA_DB.CORE.CLIENT) AS DIFFERENCE
UNION ALL
SELECT 'PORTFOLIOS',
       (SELECT COUNT(*) FROM IPRA_DB.STAGING.PORTFOLIO_STAGE),
       (SELECT COUNT(*) FROM IPRA_DB.CORE.PORTFOLIO),
       (SELECT COUNT(*) FROM IPRA_DB.STAGING.PORTFOLIO_STAGE) - 
       (SELECT COUNT(*) FROM IPRA_DB.CORE.PORTFOLIO)
UNION ALL
SELECT 'SECURITIES',
       (SELECT COUNT(*) FROM IPRA_DB.STAGING.SECURITY_STAGE),
       (SELECT COUNT(*) FROM IPRA_DB.CORE.SECURITY),
       (SELECT COUNT(*) FROM IPRA_DB.STAGING.SECURITY_STAGE) - 
       (SELECT COUNT(*) FROM IPRA_DB.CORE.SECURITY)
UNION ALL
SELECT 'HOLDINGS',
       (SELECT COUNT(*) FROM IPRA_DB.STAGING.HOLDING_STAGE),
       (SELECT COUNT(*) FROM IPRA_DB.CORE.HOLDING),
       (SELECT COUNT(*) FROM IPRA_DB.STAGING.HOLDING_STAGE) - 
       (SELECT COUNT(*) FROM IPRA_DB.CORE.HOLDING)
UNION ALL
SELECT 'PERFORMANCE',
       (SELECT COUNT(*) FROM IPRA_DB.STAGING.PERFORMANCE_STAGE),
       (SELECT COUNT(*) FROM IPRA_DB.CORE.PORTFOLIO_PERFORMANCE),
       (SELECT COUNT(*) FROM IPRA_DB.STAGING.PERFORMANCE_STAGE) - 
       (SELECT COUNT(*) FROM IPRA_DB.CORE.PORTFOLIO_PERFORMANCE);

-- 2. Total portfolio value reconciliation
SELECT 'PORTFOLIO_TOTAL_VALUE' AS RECONCILIATION_CHECK,
       (SELECT SUM(CURRENT_VALUE) FROM IPRA_DB.CORE.PORTFOLIO) AS CORE_TOTAL,
       (SELECT SUM(ENDING_VALUE) FROM IPRA_DB.CORE.PORTFOLIO_PERFORMANCE 
        WHERE AS_OF_DATE = (SELECT MAX(AS_OF_DATE) FROM IPRA_DB.CORE.PORTFOLIO_PERFORMANCE)) AS PERFORMANCE_TOTAL;