
WITH portfolio_allocation AS (
    SELECT PORTFOLIO_ID,
           SUM(MARKET_VALUE) AS PORTFOLIO_TOTAL,
           COUNT(*) AS HOLDING_COUNT
    FROM IPRA_DB.CORE.HOLDING
    GROUP BY PORTFOLIO_ID
)
SELECT 'ALLOCATION_CHECK' AS CHECK_NAME,
       PORTFOLIO_ID,
       PORTFOLIO_TOTAL,
       HOLDING_COUNT
FROM portfolio_allocation
WHERE HOLDING_COUNT > 0;

-- 2. Check return calculations
SELECT 'RETURN_CALCULATION_CHECK' AS CHECK_NAME,
       PORTFOLIO_ID,
       INITIAL_VALUE,
       CURRENT_VALUE,
       RETURN_AMOUNT,
       RETURN_PERCENT,
       ((CURRENT_VALUE - INITIAL_VALUE) / NULLIF(INITIAL_VALUE, 0)) * 100 AS CALCULATED_RETURN
FROM IPRA_DB.CORE.PORTFOLIO
WHERE ABS(RETURN_PERCENT - (((CURRENT_VALUE - INITIAL_VALUE) / NULLIF(INITIAL_VALUE, 0)) * 100)) > 0.01;