CREATE DATABASE IF NOT EXISTS IPRA_DB;
CREATE SCHEMA IF NOT EXISTS IPRA_DB.RAW;
CREATE SCHEMA IF NOT EXISTS IPRA_DB.STAGING;
CREATE SCHEMA IF NOT EXISTS IPRA_DB.CORE;
CREATE SCHEMA IF NOT EXISTS IPRA_DB.ANALYTICS;
SHOW SCHEMAS IN DATABASE IPRA_DB;
USE DATABASE IPRA_DB;
USE SCHEMA CORE;