-- CLIENT Table
CREATE OR REPLACE TABLE IPRA_DB.CORE.CLIENT (
    CLIENT_ID VARCHAR(20) NOT NULL,
    CLIENT_NAME VARCHAR(200) NOT NULL,
    CLIENT_TYPE VARCHAR(30) NOT NULL,
    COUNTRY VARCHAR(10) NOT NULL,
    RISK_PROFILE VARCHAR(20) NOT NULL,
    CREATED_DATE DATE NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Client master data - trusted business entity';

ALTER TABLE IPRA_DB.CORE.CLIENT
ADD CONSTRAINT PK_CLIENT PRIMARY KEY (CLIENT_ID);

CREATE OR REPLACE TABLE IPRA_DB.CORE.PORTFOLIO (
    PORTFOLIO_ID VARCHAR(20) NOT NULL,
    CLIENT_ID VARCHAR(20) NOT NULL,
    PORTFOLIO_NAME VARCHAR(200) NOT NULL,
    PORTFOLIO_TYPE VARCHAR(50) NOT NULL,
    BASE_CURRENCY VARCHAR(10) NOT NULL,
    RISK_PROFILE VARCHAR(20) NOT NULL,
    INITIAL_VALUE NUMBER(18,2) NOT NULL,
    CURRENT_VALUE NUMBER(18,2) NOT NULL,
    INCEPTION_DATE DATE NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Portfolio master data - trusted business entity';
ALTER TABLE IPRA_DB.CORE.PORTFOLIO
ADD CONSTRAINT PK_PORTFOLIO PRIMARY KEY (PORTFOLIO_ID);
ALTER TABLE IPRA_DB.CORE.PORTFOLIO
ADD CONSTRAINT FK_PORTFOLIO_CLIENT
FOREIGN KEY (CLIENT_ID)
REFERENCES IPRA_DB.CORE.CLIENT(CLIENT_ID);