CREATE OR REPLACE TABLE IPRA_DB.CORE.SECURITY (
    SECURITY_ID VARCHAR(20) NOT NULL,
    TICKER_SYMBOL VARCHAR(30) NOT NULL,
    SECURITY_NAME VARCHAR(200) NOT NULL,
    SECURITY_TYPE VARCHAR(30) NOT NULL,
    SECTOR VARCHAR(100),
    COUNTRY VARCHAR(10),
    CURRENCY VARCHAR(10),
    CURRENT_PRICE NUMBER(18,4) NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Security master data - trusted business entity';

ALTER TABLE IPRA_DB.CORE.SECURITY
ADD CONSTRAINT PK_SECURITY PRIMARY KEY (SECURITY_ID);

CREATE OR REPLACE TABLE IPRA_DB.CORE.HOLDING (
    HOLDING_ID VARCHAR(30) NOT NULL,
    PORTFOLIO_ID VARCHAR(20) NOT NULL,
    SECURITY_ID VARCHAR(20) NOT NULL,
    QUANTITY NUMBER(20,4) NOT NULL,
    PURCHASE_PRICE NUMBER(18,4) NOT NULL,
    CURRENT_PRICE NUMBER(18,4) NOT NULL,
    MARKET_VALUE NUMBER(18,2) NOT NULL,
    AS_OF_DATE DATE NOT NULL,
    LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Portfolio security holdings - trusted business entity';

ALTER TABLE IPRA_DB.CORE.HOLDING
ADD CONSTRAINT PK_HOLDING PRIMARY KEY (HOLDING_ID);
ALTER TABLE IPRA_DB.CORE.HOLDING
ADD CONSTRAINT FK_HOLDING_PORTFOLIO
FOREIGN KEY (PORTFOLIO_ID)
REFERENCES IPRA_DB.CORE.PORTFOLIO(PORTFOLIO_ID);
ALTER TABLE IPRA_DB.CORE.HOLDING
ADD CONSTRAINT FK_HOLDING_SECURITY
FOREIGN KEY (SECURITY_ID)
REFERENCES IPRA_DB.CORE.SECURITY(SECURITY_ID);