
-- PORTFOLIO_PERFORMANCE Table
CREATE OR REPLACE TABLE IPRA_DB.CORE.PORTFOLIO_PERFORMANCE (
    PERFORMANCE_ID VARCHAR(30) NOT NULL,
    PORTFOLIO_ID VARCHAR(20) NOT NULL,
    AS_OF_DATE DATE NOT NULL,
    BEGINNING_VALUE NUMBER(18,2) NOT NULL,
    ENDING_VALUE NUMBER(18,2) NOT NULL,
    RETURN_AMOUNT NUMBER(18,2) NOT NULL,
    RETURN_PERCENT NUMBER(12,4) NOT NULL,
    LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Historical portfolio performance - trusted business entity';

ALTER TABLE IPRA_DB.CORE.PORTFOLIO_PERFORMANCE
ADD CONSTRAINT PK_PERFORMANCE PRIMARY KEY (PERFORMANCE_ID);

ALTER TABLE IPRA_DB.CORE.PORTFOLIO_PERFORMANCE
ADD CONSTRAINT FK_PERFORMANCE_PORTFOLIO
FOREIGN KEY (PORTFOLIO_ID)
REFERENCES IPRA_DB.CORE.PORTFOLIO(PORTFOLIO_ID);