MERGE INTO IPRA_DB.CORE.CLIENT AS target
USING IPRA_DB.STAGING.CLIENT_STAGE AS source
    ON target.CLIENT_ID = source.CLIENT_ID
WHEN MATCHED THEN UPDATE SET
    target.CLIENT_NAME = source.CLIENT_NAME,
    target.CLIENT_TYPE = source.CLIENT_TYPE,
    target.COUNTRY = source.COUNTRY,
    target.RISK_PROFILE = source.RISK_PROFILE,
    target.STATUS = source.STATUS,
    target.LOAD_TS = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
    CLIENT_ID, CLIENT_NAME, CLIENT_TYPE, COUNTRY,
    RISK_PROFILE, CREATED_DATE, STATUS, LOAD_TS
) VALUES (
    source.CLIENT_ID, source.CLIENT_NAME, source.CLIENT_TYPE, source.COUNTRY,
    source.RISK_PROFILE, TO_DATE(source.CREATED_DATE), source.STATUS, CURRENT_TIMESTAMP()
);