MERGE INTO IPRA_DB.CORE.PORTFOLIO AS target
USING IPRA_DB.STAGING.PORTFOLIO_STAGE AS source
    ON target.PORTFOLIO_ID = source.PORTFOLIO_ID
WHEN MATCHED THEN UPDATE SET
    target.CLIENT_ID = source.CLIENT_ID,
    target.PORTFOLIO_NAME = source.PORTFOLIO_NAME,
    target.PORTFOLIO_TYPE = source.PORTFOLIO_TYPE,
    target.BASE_CURRENCY = source.BASE_CURRENCY,
    target.RISK_PROFILE = source.RISK_PROFILE,
    target.INITIAL_VALUE = TO_DECIMAL(source.INITIAL_VALUE, 18, 2),
    target.CURRENT_VALUE = TO_DECIMAL(source.CURRENT_VALUE, 18, 2),
    target.STATUS = source.STATUS,
    target.LOAD_TS = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
    PORTFOLIO_ID, CLIENT_ID, PORTFOLIO_NAME, PORTFOLIO_TYPE,
    BASE_CURRENCY, RISK_PROFILE, INITIAL_VALUE, CURRENT_VALUE,
    INCEPTION_DATE, STATUS, LOAD_TS
) VALUES (
    source.PORTFOLIO_ID, source.CLIENT_ID, source.PORTFOLIO_NAME, source.PORTFOLIO_TYPE,
    source.BASE_CURRENCY, source.RISK_PROFILE,
    TO_DECIMAL(source.INITIAL_VALUE, 18, 2),
    TO_DECIMAL(source.CURRENT_VALUE, 18, 2),
    TO_DATE(source.INCEPTION_DATE), source.STATUS, CURRENT_TIMESTAMP()
);