MERGE INTO IPRA_DB.CORE.SECURITY AS target
USING IPRA_DB.STAGING.SECURITY_STAGE AS source
    ON target.SECURITY_ID = source.SECURITY_ID
WHEN MATCHED THEN UPDATE SET
    target.TICKER_SYMBOL = source.TICKER_SYMBOL,
    target.SECURITY_NAME = source.SECURITY_NAME,
    target.SECURITY_TYPE = source.SECURITY_TYPE,
    target.SECTOR = source.SECTOR,
    target.COUNTRY = source.COUNTRY,
    target.CURRENCY = source.CURRENCY,
    target.CURRENT_PRICE = TO_DECIMAL(source.CURRENT_PRICE, 18, 4),
    target.STATUS = source.STATUS,
    target.LOAD_TS = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
    SECURITY_ID, TICKER_SYMBOL, SECURITY_NAME, SECURITY_TYPE,
    SECTOR, COUNTRY, CURRENCY, CURRENT_PRICE, STATUS, LOAD_TS
) VALUES (
    source.SECURITY_ID, source.TICKER_SYMBOL, source.SECURITY_NAME, source.SECURITY_TYPE,
    source.SECTOR, source.COUNTRY, source.CURRENCY,
    TO_DECIMAL(source.CURRENT_PRICE, 18, 4), source.STATUS, CURRENT_TIMESTAMP()
);