MERGE INTO IPRA_DB.CORE.HOLDING AS target
USING IPRA_DB.STAGING.HOLDING_STAGE AS source
    ON target.HOLDING_ID = source.HOLDING_ID
WHEN MATCHED THEN UPDATE SET
    target.PORTFOLIO_ID = source.PORTFOLIO_ID,
    target.SECURITY_ID = source.SECURITY_ID,
    target.QUANTITY = TO_DECIMAL(source.QUANTITY, 20, 4),
    target.PURCHASE_PRICE = TO_DECIMAL(source.PURCHASE_PRICE, 18, 4),
    target.CURRENT_PRICE = TO_DECIMAL(source.CURRENT_PRICE, 18, 4),
    target.MARKET_VALUE = TO_DECIMAL(source.MARKET_VALUE, 18, 2),
    target.AS_OF_DATE = TO_DATE(source.AS_OF_DATE),
    target.LOAD_TS = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
    HOLDING_ID, PORTFOLIO_ID, SECURITY_ID, QUANTITY,
    PURCHASE_PRICE, CURRENT_PRICE, MARKET_VALUE, AS_OF_DATE, LOAD_TS
) VALUES (
    source.HOLDING_ID, source.PORTFOLIO_ID, source.SECURITY_ID,
    TO_DECIMAL(source.QUANTITY, 20, 4),
    TO_DECIMAL(source.PURCHASE_PRICE, 18, 4),
    TO_DECIMAL(source.CURRENT_PRICE, 18, 4),
    TO_DECIMAL(source.MARKET_VALUE, 18, 2),
    TO_DATE(source.AS_OF_DATE),
    CURRENT_TIMESTAMP()
);