MERGE INTO IPRA_DB.CORE.PORTFOLIO_PERFORMANCE AS target
USING IPRA_DB.STAGING.PERFORMANCE_STAGE AS source
    ON target.PERFORMANCE_ID = source.PERFORMANCE_ID
WHEN MATCHED THEN UPDATE SET
    target.PORTFOLIO_ID = source.PORTFOLIO_ID,
    target.AS_OF_DATE = TO_DATE(source.AS_OF_DATE),
    target.BEGINNING_VALUE = TO_DECIMAL(source.BEGINNING_VALUE, 18, 2),
    target.ENDING_VALUE = TO_DECIMAL(source.ENDING_VALUE, 18, 2),
    target.RETURN_AMOUNT = TO_DECIMAL(source.RETURN_AMOUNT, 18, 2),
    target.RETURN_PERCENT = TO_DECIMAL(source.RETURN_PERCENT, 12, 4),
    target.LOAD_TS = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
    PERFORMANCE_ID, PORTFOLIO_ID, AS_OF_DATE, BEGINNING_VALUE,
    ENDING_VALUE, RETURN_AMOUNT, RETURN_PERCENT, LOAD_TS
) VALUES (
    source.PERFORMANCE_ID, source.PORTFOLIO_ID, TO_DATE(source.AS_OF_DATE),
    TO_DECIMAL(source.BEGINNING_VALUE, 18, 2),
    TO_DECIMAL(source.ENDING_VALUE, 18, 2),
    TO_DECIMAL(source.RETURN_AMOUNT, 18, 2),
    TO_DECIMAL(source.RETURN_PERCENT, 12, 4),
    CURRENT_TIMESTAMP()
);