CREATE OR REPLACE VIEW IPRA_DB.ANALYTICS.V_PORTFOLIO_SUMMARY AS
WITH holdings_aggregated AS (
    SELECT 
        PORTFOLIO_ID,
        COUNT(*) AS HOLDING_COUNT,
        SUM(MARKET_VALUE) AS TOTAL_MARKET_VALUE
    FROM IPRA_DB.CORE.HOLDING
    GROUP BY PORTFOLIO_ID
),
latest_performance AS (
    SELECT 
        PORTFOLIO_ID,
        AS_OF_DATE AS LATEST_PERFORMANCE_DATE,
        ROW_NUMBER() OVER (PARTITION BY PORTFOLIO_ID ORDER BY AS_OF_DATE DESC) AS RN
    FROM IPRA_DB.CORE.PORTFOLIO_PERFORMANCE
)
SELECT 
    p.PORTFOLIO_ID,
    p.CLIENT_ID,
    p.PORTFOLIO_NAME,
    p.PORTFOLIO_TYPE,
    p.BASE_CURRENCY,
    p.RISK_PROFILE,
    p.INITIAL_VALUE,
    p.CURRENT_VALUE,
    (p.CURRENT_VALUE - p.INITIAL_VALUE) AS RETURN_AMOUNT,
    ROUND(((p.CURRENT_VALUE - p.INITIAL_VALUE) / NULLIF(p.INITIAL_VALUE, 0)) * 100, 4) AS RETURN_PERCENT,
    COALESCE(h.TOTAL_MARKET_VALUE, 0) AS TOTAL_MARKET_VALUE,
    COALESCE(h.HOLDING_COUNT, 0) AS HOLDING_COUNT,
    lp.LATEST_PERFORMANCE_DATE,
    p.STATUS,
    p.INCEPTION_DATE
FROM IPRA_DB.CORE.PORTFOLIO p
LEFT JOIN holdings_aggregated h ON p.PORTFOLIO_ID = h.PORTFOLIO_ID
LEFT JOIN latest_performance lp ON p.PORTFOLIO_ID = lp.PORTFOLIO_ID AND lp.RN = 1;