CREATE OR REPLACE VIEW IPRA_DB.ANALYTICS.V_PORTFOLIO_HOLDINGS AS
SELECT 
    h.HOLDING_ID,
    h.PORTFOLIO_ID,
    h.SECURITY_ID,
    s.TICKER_SYMBOL,
    s.SECURITY_NAME,
    s.SECURITY_TYPE,
    s.SECTOR,
    s.COUNTRY AS SECURITY_COUNTRY,
    s.CURRENCY AS SECURITY_CURRENCY,
    h.QUANTITY,
    h.PURCHASE_PRICE,
    h.CURRENT_PRICE,
    h.MARKET_VALUE,
    h.AS_OF_DATE,
    p.PORTFOLIO_NAME,
    p.CLIENT_ID,
    c.CLIENT_NAME
FROM IPRA_DB.CORE.HOLDING h
JOIN IPRA_DB.CORE.PORTFOLIO p ON h.PORTFOLIO_ID = p.PORTFOLIO_ID
JOIN IPRA_DB.CORE.SECURITY s ON h.SECURITY_ID = s.SECURITY_ID
JOIN IPRA_DB.CORE.CLIENT c ON p.CLIENT_ID = c.CLIENT_ID;