CREATE OR REPLACE VIEW IPRA_DB.ANALYTICS.V_PORTFOLIO_ALLOCATION AS
WITH portfolio_totals AS (
    SELECT 
        PORTFOLIO_ID,
        SUM(MARKET_VALUE) AS TOTAL_MARKET_VALUE
    FROM IPRA_DB.CORE.HOLDING
    GROUP BY PORTFOLIO_ID
)
SELECT 
    h.PORTFOLIO_ID,
    h.SECURITY_ID,
    s.TICKER_SYMBOL AS SECURITY_NAME,
    s.SECTOR,
    s.COUNTRY AS SECURITY_COUNTRY,
    h.MARKET_VALUE AS SECURITY_MARKET_VALUE,
    ROUND((h.MARKET_VALUE / NULLIF(pt.TOTAL_MARKET_VALUE, 0)) * 100, 2) AS SECURITY_ALLOCATION_PERCENT,
    ROUND((SUM(h.MARKET_VALUE) OVER (PARTITION BY h.PORTFOLIO_ID, s.SECTOR) / NULLIF(pt.TOTAL_MARKET_VALUE, 0)) * 100, 2) AS SECTOR_ALLOCATION_PERCENT,
    ROUND((SUM(h.MARKET_VALUE) OVER (PARTITION BY h.PORTFOLIO_ID, s.COUNTRY) / NULLIF(pt.TOTAL_MARKET_VALUE, 0)) * 100, 2) AS COUNTRY_ALLOCATION_PERCENT,
    pt.TOTAL_MARKET_VALUE AS PORTFOLIO_TOTAL_VALUE,
    h.AS_OF_DATE
FROM IPRA_DB.CORE.HOLDING h
JOIN IPRA_DB.CORE.SECURITY s ON h.SECURITY_ID = s.SECURITY_ID
JOIN portfolio_totals pt ON h.PORTFOLIO_ID = pt.PORTFOLIO_ID;