CREATE OR REPLACE VIEW IPRA_DB.ANALYTICS.V_PORTFOLIO_PERFORMANCE AS
SELECT 
    p.PERFORMANCE_ID,
    p.PORTFOLIO_ID,
    p.AS_OF_DATE,
    p.BEGINNING_VALUE,
    p.ENDING_VALUE,
    p.RETURN_AMOUNT,
    p.RETURN_PERCENT,
    LAG(p.ENDING_VALUE) OVER (PARTITION BY p.PORTFOLIO_ID ORDER BY p.AS_OF_DATE) AS PREVIOUS_VALUE,
    ROUND(
        ((p.ENDING_VALUE - LAG(p.ENDING_VALUE) OVER (PARTITION BY p.PORTFOLIO_ID ORDER BY p.AS_OF_DATE)) 
         / NULLIF(LAG(p.ENDING_VALUE) OVER (PARTITION BY p.PORTFOLIO_ID ORDER BY p.AS_OF_DATE), 0)) * 100, 
        4
    ) AS PERIOD_OVER_PERIOD_RETURN,
    po.PORTFOLIO_NAME,
    po.CLIENT_ID
FROM IPRA_DB.CORE.PORTFOLIO_PERFORMANCE p
JOIN IPRA_DB.CORE.PORTFOLIO po ON p.PORTFOLIO_ID = po.PORTFOLIO_ID
ORDER BY p.PORTFOLIO_ID, p.AS_OF_DATE;