CREATE OR REPLACE VIEW IPRA_DB.ANALYTICS.V_PORTFOLIO_RISK AS
WITH security_concentration AS (
    SELECT 
        PORTFOLIO_ID,
        SECURITY_ID,
        MARKET_VALUE,
        ROW_NUMBER() OVER (PARTITION BY PORTFOLIO_ID ORDER BY MARKET_VALUE DESC) AS RN,
        SUM(MARKET_VALUE) OVER (PARTITION BY PORTFOLIO_ID) AS PORTFOLIO_TOTAL
    FROM IPRA_DB.CORE.HOLDING
),
highest_holding AS (
    SELECT 
        PORTFOLIO_ID,
        SECURITY_ID,
        MARKET_VALUE,
        ROUND((MARKET_VALUE / NULLIF(PORTFOLIO_TOTAL, 0)) * 100, 2) AS HIGHEST_WEIGHT_PERCENT
    FROM security_concentration
    WHERE RN = 1
)
SELECT 
    p.PORTFOLIO_ID,
    p.CLIENT_ID,
    p.PORTFOLIO_NAME,
    p.RISK_PROFILE AS PORTFOLIO_RISK_PROFILE,
    hh.SECURITY_ID AS HIGHEST_HOLDING_SECURITY_ID,
    hh.MARKET_VALUE AS HIGHEST_HOLDING_VALUE,
    hh.HIGHEST_WEIGHT_PERCENT,
    CASE 
        WHEN hh.HIGHEST_WEIGHT_PERCENT > 40 THEN 'HIGH'
        WHEN hh.HIGHEST_WEIGHT_PERCENT > 25 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS CONCENTRATION_RISK,
    CASE 
        WHEN p.RISK_PROFILE = 'HIGH' OR hh.HIGHEST_WEIGHT_PERCENT > 40 THEN 'CRITICAL'
        WHEN p.RISK_PROFILE = 'MEDIUM' OR hh.HIGHEST_WEIGHT_PERCENT > 25 THEN 'REVIEW'
        ELSE 'NORMAL'
    END AS RISK_STATUS,
    CASE 
        WHEN hh.HIGHEST_WEIGHT_PERCENT > 40 THEN 'Highest security weight exceeds 40% - HIGH concentration risk'
        WHEN hh.HIGHEST_WEIGHT_PERCENT > 25 THEN 'Highest security weight exceeds 25% - MEDIUM concentration risk'
        WHEN p.RISK_PROFILE = 'HIGH' THEN 'Portfolio risk profile is HIGH'
        ELSE 'No critical risk indicators detected'
    END AS RISK_EXPLANATION,
    p.CURRENT_VALUE,
    p.TOTAL_MARKET_VALUE,
    p.HOLDING_COUNT,
    CURRENT_TIMESTAMP() AS ANALYZED_AT
FROM IPRA_DB.ANALYTICS.V_PORTFOLIO_SUMMARY p
LEFT JOIN highest_holding hh ON p.PORTFOLIO_ID = hh.PORTFOLIO_ID;