CREATE OR REPLACE VIEW IPRA_DB.ANALYTICS.V_CLIENT_PORTFOLIO_SUMMARY AS
SELECT 
    c.CLIENT_ID,
    c.CLIENT_NAME,
    c.CLIENT_TYPE,
    c.COUNTRY AS CLIENT_COUNTRY,
    c.RISK_PROFILE AS CLIENT_RISK_PROFILE,
    COUNT(DISTINCT p.PORTFOLIO_ID) AS PORTFOLIO_COUNT,
    SUM(p.TOTAL_MARKET_VALUE) AS TOTAL_PORTFOLIO_VALUE,
    ROUND(AVG(p.RETURN_PERCENT), 2) AS AVERAGE_RETURN_PERCENT,
    COUNT(DISTINCT CASE WHEN p.RISK_PROFILE = 'HIGH' THEN p.PORTFOLIO_ID END) AS HIGH_RISK_PORTFOLIO_COUNT,
    COUNT(DISTINCT CASE WHEN p.RISK_PROFILE = 'MEDIUM' THEN p.PORTFOLIO_ID END) AS MEDIUM_RISK_PORTFOLIO_COUNT,
    COUNT(DISTINCT CASE WHEN p.RISK_PROFILE = 'LOW' THEN p.PORTFOLIO_ID END) AS LOW_RISK_PORTFOLIO_COUNT,
    c.STATUS AS CLIENT_STATUS,
    c.CREATED_DATE
FROM IPRA_DB.CORE.CLIENT c
LEFT JOIN IPRA_DB.ANALYTICS.V_PORTFOLIO_SUMMARY p ON c.CLIENT_ID = p.CLIENT_ID
GROUP BY c.CLIENT_ID, c.CLIENT_NAME, c.CLIENT_TYPE, c.COUNTRY, c.RISK_PROFILE, c.STATUS, c.CREATED_DATE;